#!/bin/sh

## Bash Script to clear cached memory on (Ubuntu) Linux
## see <http://blog.philippklaus.de/2011/02/clear-cached-memory-on-ubuntu/>

freemem_before=`cat /proc/meminfo | grep MemFree | tr -s ' ' | cut -d ' ' -f2`
freemem_before=`echo "$freemem_before/1024.0" | bc`
cachedmem_before=`cat /proc/meminfo | grep "^Cached" | tr -s ' ' | cut -d ' ' -f2`
cachedmem_before=`echo "$cachedmem_before/1024.0" | bc`

printf "This script will clear cached memory and free up your ram. At the moment you have $cachedmem_before MiB cached and $freemem_before MiB free memory."

sudo sync
#echo "sync; echo 3 > /proc/sys/vm/drop_caches" | sudo su
echo "echo 3 > /proc/sys/vm/drop_caches" | sudo su
freemem_after=`cat /proc/meminfo | grep MemFree | tr -s ' ' | cut -d ' ' -f2`
freemem_after=`echo "$freemem_after/1024.0" | bc`

printf "%s\n" "" "This freed `echo "$freemem_after - $freemem_before" | bc` MiB, so now you have $freemem_after MiB of free RAM."
